name: docs-build
on:
    pull_request:
        branches:
            - main
            - master

jobs:
    test-docs-build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - uses: actions/setup-python@v5
              with:
                  python-version: "3.11"
            - name: Install GDAL
              run: |
                  python -m pip install --upgrade pip
                  pip install --find-links=https://girder.github.io/large_image_wheels --no-cache GDAL pyproj
            - name: Test GDAL installation
              run: |
                  python -c "from osgeo import gdal"
                  gdalinfo --version
            - name: Install dependencies
              run: |
                  pip install --no-cache-dir Cython
                  pip install -r requirements.txt -r requirements_dev.txt
                  pip install .
            - name: PKG-TEST
              run: |
                  python -m unittest discover tests/
            - name: Build docs
              run: |
                  mkdocs build
              env:
                  EARTHDATA_USERNAME: ${{ secrets.EARTHDATA_USERNAME }}
                  EARTHDATA_PASSWORD: ${{ secrets.EARTHDATA_PASSWORD }}
            - name: Deploy to Netlify
              uses: nwtgck/actions-netlify@v3.0
              with:
                  publish-dir: "./site"
                  production-branch: main

                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  deploy-message: "Deploy from GitHub Actions"
                  enable-pull-request-comment: true
                  enable-commit-comment: false
                  overwrites-pull-request-comment: true
              env:
                  NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
                  NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
              timeout-minutes: 10
