name: test-earthdata
on:
    pull_request:
        branches:
            - main
            - master

jobs:
    test-earthdata:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - uses: actions/setup-python@v5
              with:
                  python-version: "3.11"
              env:
                  EARTHDATA_USERNAME: ${{ secrets.EARTHDATA_USERNAME }}
                  EARTHDATA_PASSWORD: ${{ secrets.EARTHDATA_PASSWORD }}

            - name: Install GDAL
              run: |
                  python -m pip install --upgrade pip
                  pip install --find-links=https://girder.github.io/large_image_wheels --no-cache GDAL pyproj
            - name: Test GDAL installation
              run: |
                  python -c "from osgeo import gdal"
                  gdalinfo --version
            - name: Install dependencies
              run: |
                  pip install --no-cache-dir Cython
                  pip install -r requirements.txt -r requirements_dev.txt
                  pip install .
            - name: Test import
              run: python -c "import earthaccess;print(earthaccess.login(strategy='environment').authenticated)"
